trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'
container: adoptopenjdk:11-jdk-hotspot
steps:
- script: $(Pipeline.Workspace)/s/gradlew build --stacktrace
  displayName: 'Clone and build xp core'
- task: CopyFiles@2
  inputs:
    Contents: $(Build.SourcesDirectory)/modules/runtime/build
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: xp-core
